# Generated by Django 2.0.5 on 2018-05-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0002_auto_20180531_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poetry',
            name='dynasty',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='poetry_author',
            name='dynasty',
            field=models.CharField(max_length=10),
        ),
    ]
