# Generated by Django 2.0.5 on 2018-06-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0003_auto_20180531_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='poems',
            name='clickcount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poems_author',
            name='clickcount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poetry',
            name='clickcount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poetry_author',
            name='clickcount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='poems',
            name='dynasty',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='poems_author',
            name='dynasty',
            field=models.CharField(max_length=10),
        ),
    ]
