# Generated by Django 2.0.5 on 2018-06-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0006_auto_20180604_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poems',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='poetry',
            name='content',
            field=models.TextField(),
        ),
    ]
